export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'backend',
        'frontend',
        'shared',
        'analytics',
        'infra',
        'db',
        'deps',
        'ci',
        'docs',
        'docker',
        'auth',
        'pos',
        'inventory',
        'hr',
        'crm',
        'accounting',
        'analytics',
        'integrations',
        'subscriptions',
        'onboarding',
        'super-admin',
        'waiter',
      ],
    ],
    'subject-case': [2, 'always', 'lower-case'],
    'header-max-length': [2, 'always', 100],
  },
};
