tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#eceef0",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-container": "#57657b",
        "surface-container-high": "#e6e8ea",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#d5e3fd",
        "on-primary": "#ffffff",
        "surface-tint": "#4059aa",
        "secondary-fixed-dim": "#b9c7e0",
        "primary-container": "#1e3a8a",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d8dadc",
        "inverse-primary": "#b6c4ff",
        "on-surface": "#191c1e",
        "on-primary-fixed-variant": "#264191",
        "surface": "#f7f9fb",
        "on-tertiary-fixed-variant": "#005236",
        "tertiary-fixed-dim": "#4edea3",
        "secondary-container": "#d5e3fd",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-highest": "#e0e3e5",
        "outline": "#757682",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-container": "#27c38a",
        "outline-variant": "#c5c5d3",
        "background": "#f7f9fb",
        "on-surface-variant": "#444651",
        "primary-fixed-dim": "#b6c4ff",
        "tertiary": "#00311f",
        "surface-variant": "#e0e3e5",
        "error-container": "#ffdad6",
        "tertiary-container": "#004a31",
        "primary": "#00236f",
        "on-secondary-fixed-variant": "#3a485c",
        "inverse-surface": "#2d3133",
        "on-background": "#191c1e",
        "surface-container-low": "#f2f4f6",
        "on-primary-fixed": "#00164e",
        "on-secondary-fixed": "#0d1c2f",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "secondary": "#515f74",
        "primary-fixed": "#dce1ff",
        "on-primary-container": "#90a8ff",
        "on-error": "#ffffff"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        lg: "24px",
        sm: "8px",
        "container-max": "1440px",
        xl: "32px",
        md: "16px",
        base: "4px",
        xs: "4px",
        gutter: "16px"
      },
      fontFamily: {
        "display-lg": ["Inter"],
        "data-mono": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg": ["Inter"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }]
      }
    }
  }
};
